"""
Django settings for secure_attendance project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv#type: ignore

load_dotenv()


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ["*", "localhost",
    "127.0.0.1",
    "192.168.137.1",]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',

    'rest_framework',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # HotspotRestrictionMiddleware removed — network verification handled by Attendance Agent
]

ROOT_URLCONF = 'secure_attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'secure_attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'

# ---------- SECURE PRESENCE PHASE 2 SETTINGS ----------
SECURE_PRESENCE_V2_ENABLED = os.getenv("SECURE_PRESENCE_V2_ENABLED", "True") == "True"
PRESENCE_HEARTBEAT_MAX_AGE_SECONDS = int(os.getenv("PRESENCE_HEARTBEAT_MAX_AGE_SECONDS", "45"))

# rpId must be a valid domain name — IP addresses are rejected by WebAuthn spec.
# sslip.io is a free public DNS service: 192-168-137-1.sslip.io resolves to 192.168.137.1.
# Students' phones resolve this via DNS through the hotspot's shared internet connection.
WEBAUTHN_RP_ID = os.getenv("WEBAUTHN_RP_ID", "192-168-137-1.sslip.io")
WEBAUTHN_RP_NAME = os.getenv("WEBAUTHN_RP_NAME", "Secure Attendance System")
WEBAUTHN_ORIGIN = os.getenv("WEBAUTHN_ORIGIN", "https://192-168-137-1.sslip.io:8000")

# Cache backend for rate limiting & ephemeral challenges
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'secure-presence-cache',
    }
}

LIVENESS_VERIFIER_TYPE = os.getenv("LIVENESS_VERIFIER_TYPE", "mediapipe")

# ---------- ATTENDANCE AGENT SETTINGS ----------
# URL of the local Attendance Agent HTTP server
# In dev: Agent runs on the same machine as Django (localhost:5000)
# In production: Agent runs on professor's laptop; Django can be cloud-hosted
ATTENDANCE_AGENT_URL = os.getenv("ATTENDANCE_AGENT_URL", "http://127.0.0.1:5000")

# Pre-shared bearer token for Django ↔ Agent communication
# Must match the api_token in attendance_agent.toml / ATTENDANCE_AGENT_API_TOKEN env var on the Agent
ATTENDANCE_AGENT_API_TOKEN = os.getenv("ATTENDANCE_AGENT_API_TOKEN", "secure_presence_v3_default_token")

# Seconds a challenge nonce is valid (must match Agent's challenge_ttl_seconds)
ATTENDANCE_AGENT_CHALLENGE_TTL_SECONDS = int(os.getenv("ATTENDANCE_AGENT_CHALLENGE_TTL_SECONDS", "30"))

# Seconds since last heartbeat before Django considers the Agent dead and closes the session
ATTENDANCE_AGENT_HEARTBEAT_MAX_AGE_SECONDS = int(os.getenv("ATTENDANCE_AGENT_HEARTBEAT_MAX_AGE_SECONDS", "90"))

# Development bypass: if True, agent challenge is optional (useful for unit tests)
ATTENDANCE_AGENT_DEV_BYPASS = os.getenv("ATTENDANCE_AGENT_DEV_BYPASS", "True") == "True"
