# Generated by Django 5.2.11 on 2026-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
