# Generated by Django 5.2.11 on 2026-02-19 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_private_key_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField()),
                ('network_nonce', models.TextField()),
                ('session_signature', models.TextField()),
                ('gateway_ip', models.GenericIPAddressField()),
                ('subnet_range', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
