# Generated by Django 5.2.11 on 2026-02-19 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField()),
                ('record_hash', models.CharField(max_length=256)),
                ('chained_hash', models.CharField(max_length=256)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
