# Generated by Django 5.2.12 on 2026-07-26 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LIVENESS_PENDING', 'Liveness Pending'), ('BIOMETRIC_VERIFIED', 'Biometric Verified'), ('CHALLENGE_ISSUED', 'Challenge Issued'), ('SIGNED', 'Signed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('signing_challenge', models.TextField(blank=True, null=True)),
                ('challenge_issued_at', models.DateTimeField(blank=True, null=True)),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_report_hash', models.CharField(max_length=64)),
                ('previous_entry_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('entry_signature', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('verification_references', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSessionAuditRoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_hash', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LivenessVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error')], max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('verifier_name', models.CharField(max_length=100)),
                ('verifier_version', models.CharField(max_length=50)),
                ('reason_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('public_key', models.TextField()),
                ('sign_counter', models.BigIntegerField(default=0)),
                ('credential_metadata', models.JSONField(blank=True, default=dict)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresenceHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='security_mode',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('secure_presence_v2', 'Secure Presence V2')], default='legacy', max_length=30),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['active', 'expiry', 'security_mode'], name='core_attend_active_993b65_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['professor', 'active'], name='core_attend_profess_a838de_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['student', 'revoked'], name='core_device_student_dacfd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_session_attendance'),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceauditentry',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entry', to='core.attendancerecord'),
        ),
        migrations.AddField(
            model_name='attendanceauditentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='core.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendancesessionauditroot',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_root', to='core.attendancesession'),
        ),
        migrations.AddField(
            model_name='livenessverification',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_verification', to='core.attendanceattempt'),
        ),
        migrations.AddField(
            model_name='passkeycredential',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='passkey_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='core.passkeycredential'),
        ),
        migrations.AddField(
            model_name='presenceheartbeat',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='core.attendanceattempt'),
        ),
        migrations.AddField(
            model_name='presenceheartbeat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendanceauditentry',
            index=models.Index(fields=['session', 'signed_at'], name='core_attend_session_6a77c9_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeycredential',
            index=models.Index(fields=['student', 'revoked'], name='core_passke_student_95f2da_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceattempt',
            index=models.Index(fields=['session', 'student', 'status'], name='core_attend_session_02976f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceattempt',
            index=models.Index(fields=['status', 'expires_at'], name='core_attend_status_510396_idx'),
        ),
        migrations.AddIndex(
            model_name='presenceheartbeat',
            index=models.Index(fields=['attempt', 'student', 'timestamp'], name='core_presen_attempt_b8d6d3_idx'),
        ),
    ]
