# Generated by Django 5.2.12 on 2026-08-01 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attendanceattempt_attendanceauditentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceattempt',
            name='agent_challenge_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='agent_challenge_ts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='agent_proof_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='agent_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_secret_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='gateway_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='subnet_range',
            field=models.CharField(blank=True, default='agent', max_length=50),
        ),
        migrations.CreateModel(
            name='AttendanceAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('public_key_pem', models.TextField()),
                ('x25519_public_key_pem', models.TextField(blank=True, default='')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['agent_id'], name='core_attend_agent_i_2531da_idx'), models.Index(fields=['last_heartbeat'], name='core_attend_last_he_ec1380_idx')],
            },
        ),
    ]
