# Generated by Django 5.2.12 on 2026-09-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agent_network_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='encrypted_session_secret',
            field=models.TextField(blank=True, default=''),
        ),
    ]
